### ISSUE TITLE
iOS ConversationsClientConversationUpdated is fired?

### ISSUE THREAD

**Issue by NishiokaTakeo** [jedusei/Twilio.Conversations.Xamarin#10]
Hi, 

I am working on iOS implementation and I am trying to get to be fired on `ConversationsClientConversationUpdated()` in a class that inherited from `TwilioConversationsClientDelegate` class.  But it seems not being fired. 

**I have checked** :
`ConversationsClientSynchronizationStatusUpdated()` is fired and status can get `ConversationsListCompleted`.  In my test app, A sender sends a message to a receiver, and I can see the message in both app. However `ConversationsClientConversationUpdated(TwilioConversationsClient client, TCHConversation channel, TCHConversationUpdate updated)` is not fired at the time of sending out. 

I also checked [official document](http://media.twiliocdn.com/sdk/ios/conversations/releases/2.2.3/docs/Protocols/TwilioConversationsClientDelegate.html#//api/name/conversationsClient:conversation:updated:) but it does not help for me and [binding](https://github.com/jedusei/Twilio.Conversations.Xamarin/blob/fd700ead2ab59e7ef439117bedd40dfbc16165e6/Twilio.Conversations.iOS/ApiDefinition.cs#L1117) seems setup in this repo.

Could you help me how I can fire that method?

Any help would be really thank you.

**Comment by jedusei** [comment]
Hi @NishiokaTakeo 

First of all, you're supposed to wait for `Completed`status instead of `ConversationsListCompleted` before using the client.

Secondly, can you confirm that [ConversationListener.OnConversationUpdated](https://media.twiliocdn.com/sdk/android/conversations/releases/3.1.0/docs/-conversations%20-android%20-s-d-k/com.twilio.conversations/-conversations-client-listener/index.html#-1399403770%2FFunctions%2F68704080) is called in the Android app when a message is sent?

**Comment by NishiokaTakeo** [comment]
Hi @jedusei 

Thank you for replying. Yes. I have waited for `Completed` status and sends a message. Also [ConversationListener.OnConversationUpdated](https://media.twiliocdn.com/sdk/android/conversations/releases/3.1.0/docs/-conversations%20-android%20-s-d-k/com.twilio.conversations/-conversations-client-listener/index.html#-1399403770%2FFunctions%2F68704080) is called in Android project.

**Comment by jedusei** [comment]
Hi @NishiokaTakeo 

Alright, I'll investigate the issue on iOS. It will take a little longer to debug this issue because my MacBook is not readily available.

If you're just using `ConversationsClientConversationUpdated` to do something when a message is sent, then consider using `ConversationsClientMessageAdded` as an alternative, and let me know how that goes.

**Comment by NishiokaTakeo** [comment]
Hi @jedusei 

I will also try to investigate for this. If you have any idea I can investigate, I will do it. 

> If you're just using ConversationsClientConversationUpdated to do something when a message is sent, then consider using ConversationsClientMessageAdded as an alternative, and let me know how that goes.

It was not fired.

**Comment by NishiokaTakeo** [comment]
Hi @jedusei ,

Self managed this issue. It seems delegate instance must be created/defined in same class instance. 

**This will not call these events.** 
```
TwilioConversationsClient.ConversationsClientWithToken(
                token,
                new TwilioConversationsClientProperties(),
                new MyDelegateThatInheritedFromTwilioConversationsClientDelegate(),  <--- define the implementation of delegates in other class
                (result, chatClient) => /* do something */;
```

**This will call all events** 
```
TwilioConversationsClient.ConversationsClientWithToken(
                token,
                new TwilioConversationsClientProperties(),
                this, <--- define the implementation of delegates in same class
                (result, chatClient) => /* do something */;
```

Not sure why first one does not work. But anyway, I have got the solution. Thank you :)


**UPDATE:** 
If `MyDelegateThatInheritedFromTwilioConversationsClientDelegate `class is defined within same class as nested class and create instance like below, it will also work.

```
private TwilioClientDelegate _clientDelegate = new TwilioClientDelegate();
private class TwilioClientDelegate : TwilioConversationsClientDelegate{ /*whatever you want to override*/ }
```

```
TwilioConversationsClient.ConversationsClientWithToken(
                token,
                new TwilioConversationsClientProperties(),
                _clientDelegate , 
                (result, chatClient) => /* do something */;
```

**Comment by jedusei** [comment]
Hi @NishiokaTakeo 

Thank you very much for investigating this and coming up with a solution. I haven't had a chance to verify this behaviour myself, but I'll close this issue since you have resolved the problem.
