### ISSUE TITLE
Can't resolve the reference 'System.IntPtr ObjCRuntime.DisposableObject::get_Handle()'

### ISSUE THREAD

**Issue by NishiokaTakeo** [jedusei/Twilio.Conversations.Xamarin#11]
Hi,
I have building iOS and while doing that, it causes error below.

> MTOUCH : error MT2101: Can't resolve the reference 'System.IntPtr ObjCRuntime.DisposableObject::get_Handle()', referenced from the method 'System.Void Twilio.Conversations.TwilioConversationsClient::set_DispatchQueue(CoreFoundation.DispatchQueue)' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'. [/Users/runner/work/1/s/xxxxx/MyClient.iOS/MyClient.iOS.csproj]

Are there any changes to the required versions of Xamarin or Visual Studio?

**Comment by jedusei** [comment]
Hi @NishiokaTakeo 

Try changing the `Linker Behaviour` setting in the build options to `Don't Link`.
If that doesn't work then try updating Visual Studio to the latest version.

**Comment by NishiokaTakeo** [comment]
Hi @jedusei 

Thank you for replying, 

> Try changing the Linker Behaviour setting in the build options to Don't Link.

It did not work. I have found the solution.[ Mono iOS version must be same or above 6_12_12](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#xamarin-bundles) which is default. It was 6_12_11. 

It would be good if we can add this information to somewhere?

**Comment by jedusei** [comment]
Hi @NishiokaTakeo 

Thanks for solving the issue. I will update the readme to include this information.
