### ISSUE TITLE
iPhone App immediately crashes on physical iPhone when just load TCHConversationDelegate

### ISSUE THREAD

**Issue by NishiokaTakeo** [jedusei/Twilio.Conversations.Xamarin#12]
iPhone App crashes when a class inherited `TCHConversationDelegate` class in iOS project. 
iOS simulator on Xamarin does not crash and working fine seems all feature I am using. It crashes on **only** physical phone. It immediately crashes when app is opening. 

Only this code crashes.
`public class TwilioChannelDelegate : TCHConversationDelegate { }`

**Comment by NishiokaTakeo** [comment]
Sorry, I have cloned this repo to my local so that I can start debug. How can I get successful building? 

- Downloaded iOS SDK from [here](https://www.twilio.com/docs/conversations/sdk-download-install#ios-sdk)
- Added Native Framework References and specified below folder _C:\Users\XXX\twilio-conversations-ios-2.2.2\TwilioConversationsClient.xcframework\ios-arm64\TwilioConversationsClient.framework_

Clean & Building fails as lots of classes are not found. For example.

> The type or namespace name 'TCHUserUpdate' could not be found (are you missing a using directive or an assembly reference?)	Twilio.Conversations.iOS	

It would be great if someone help me..

**Comment by jedusei** [comment]
Hi @NishiokaTakeo 

>The type or namespace name 'TCHUserUpdate' could not be found (are you missing a using directive or an assembly reference?) Twilio.Conversations.iOS

Please make sure that `StructsAndEnums.cs` is included in the project and its build action is set to `ObjcBindingApiDefinition` before building.

If that file has already been included and its build action has been set correctly then please post the full list of build errors for me. I think maybe something else in the build process failed, leading to this error.

**Comment by NishiokaTakeo** [comment]
I have checked `StructsAndEnums.cs` is included with `ObjcBindingApiDefinition `build action.

There are 53 errors that says same as I posted. _( 'xxxxx' could not be found (are you missing a using directive or......)_
some of these classes are  :

- TCHClientSynchronizationStatus
- TCHConversationNotificationLevel
- TCHConversationStatus
- TCHConversationSynchronizationStatus
- TCHConversationSynchronizationStatus
- TCHConversationUpdate
- TCHDeliveryAmount
- TCHDeliveryStatus
- TCHLogLevel

I think sdk loading fails?

**Comment by jedusei** [comment]
This is strange...
Please answer the following questions so that I can try to figure out what the issue might be:
1. Are you building on a Mac or Windows machine?
2. Are there any build warnings?
3. What version of Visual Studio and Xamarin.iOS are you using?
4. What iPhone did the app crash on? Which iOS version are you using?

**Comment by NishiokaTakeo** [comment]
Hi @jedusei 
Thank you for helping me. The answer is below.

> Are you building on a Mac or Windows machine?

Windows

> Are there any build warnings?

There is on warnings. 
_The referenced component 'Native References/TwilioConversationsClient.framework' could not be found.	Twilio.Conversations.iOS_			

> What version of Visual Studio and Xamarin.iOS are you using?

Visual Studio is 2022. Sorry how can I know Xamarin.iOS version?

> What iPhone did the app crash on? Which iOS version are you using?

iOS is 15.5
Model Name is iPhone X

**Comment by jedusei** [comment]
Thanks for answering.

> Sorry how can I know Xamarin.iOS version?

Go to `Help > About Visual Studio` then scroll down the list to the last item.

>The referenced component 'Native References/TwilioConversationsClient.framework' could not be found. Twilio.Conversations.iOS

I think this might be why the build is failing. If the native reference is set up correctly then this warning should not appear. Copy `C:\Users\XXX\twilio-conversations-ios-2.2.2\TwilioConversationsClient.xcframework\ios-arm64\TwilioConversationsClient.framework` to the `Native References` folder of the `Twilio.Conversations.iOS` project and rebuild and let's see whether the warning is still there.

**Comment by NishiokaTakeo** [comment]
> Go to Help > About Visual Studio then scroll down the list to the last item.

Xamarin.iOS version is 15.10.0.5

> rebuild and let's see whether the warning is still there.

Still error... 

Just for the information. The files/folders under the `Native References` folder contains belows.

- _CodeSignature
- Headers
- Modules
- Info.plist
- rootcert.pem
- TwilioConversationsClient
Is these enough?

**Comment by NishiokaTakeo** [comment]
For the building issue, I have created [new PR](https://github.com/jedusei/Twilio.Conversations.Xamarin/pull/13). 

The target branch is master. Please correct me if I am wrong.

**Comment by NishiokaTakeo** [comment]
Hi @jedusei 

Sorry, Can we double check iOS SDK version for `Twilio.Conversation`? Is that same as binding `2.2.2` ?

I assume linking TCHConversationDelegate to iOS SDK's one is not happening correctly. That is reason to crash I think?

**Comment by jedusei** [comment]
Hi @NishiokaTakeo 

Sorry for the late response. I have finally been able to test this on a Mac and have been able to reproduce this issue. I will publish a new release to fix this later today. Thanks for your patience.

> That is reason to crash I think?

It's crashing because the iOS SDK included in the Nuget is designed to run only on the iOS simulator. You can check the device logs to see for yourself (on Mac, open Xcode, go to `Window > Devices and Simulators`, then click on your device and click on View Device Logs`). I will correct that in the next release (2.0.2).

**Comment by jedusei** [comment]
@NishiokaTakeo 
I want to send you the iOS dll so that you can check on your end to see whether it works, before I publish it. Are you ok with that?

**Comment by NishiokaTakeo** [comment]
Hi @jedusei 

Thank you for taking time to investigate and came up with the solution. 

> I want to send you the iOS dll so that you can check on your end to see whether it works, before I publish it. Are you ok with that?

Yes of cause. it would be great If I can receive the dll to my email address. :)

**Comment by jedusei** [comment]
Thanks @NishiokaTakeo, I've sent the download link via email.

**Comment by NishiokaTakeo** [comment]
@jedusei 

I have tried with new DLL and it does nothing changed.  But thankfully I could get logs. Here is the log. 
Here is highlight error from the log

- DYLD 1 Library missing
- incompatible platform (have 'iOS-sim', need 'iOS')

```
OS Version:          iPhone OS 15.5 (19F77)
Release Type:        User
Baseband Version:    7.61.00
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: DYLD 1 Library missing
Library not loaded: @rpath/TwilioConversationsClient.framework/TwilioConversationsClient
Referenced from: /Volumes/VOLUME/*/MyClient.iOS.app/MyClient.iOS
Reason: tried: '/private/var/containers/Bundle/Application/29A849F7-8D49-4272-9DA4-0A710FC7C875/MyClient.iOS.app/Frameworks/TwilioConversationsClient.framework/TwilioConversationsClient' (mach-o file (/private/var/containers/Bundle/Application/29A849F7-8D49-4272-9DA4-0A710FC7C875/MyClient.iOS.app/Frameworks/TwilioConversationsClient.framework/TwilioConversationsClient), but incompatible platform (have 'iOS-sim', need 'iOS')), '/private/var/containers/Bundle/Application/29A849F7-8D49-4272-9DA4-0A710FC7C875/MyClient.iOS.app/Frameworks/TwilioConversationsClient.framework/TwilioConversationsClient' (mach-o file (/private/var/containers/Bundle/Application/29A849F7-8D49-4272-9DA4-0A710FC7C875/MyClient.iOS.app/Frameworks/TwilioConversationsClient.framework/TwilioC
(terminated at launch; ignore backtrace)

```

**Comment by jedusei** [comment]
Hi @NishiokaTakeo 

I tested an app on both simulator and device and there was no crash. I believe your project is still using the DLL from the nuget package. Try these steps and let me know whether the app still crashes:

1. Remove the nuget package reference from the iOS app project if you haven't done so already.
2. Remove the reference to the DLL that I sent.
3. Clean and rebuild the project. There should be some build errors (eg. `TCHConversation` not found)
4. Add the DLL as a reference to the iOS app project.
5. Add this line of code somewhere in your project: `Console.WriteLine(TwilioConversationsClient.SdkVersion)`
6. Run the app on the simulator and let me know the output of the code in the previous step.

**Comment by NishiokaTakeo** [comment]
Hi @jedusei 

Thank you for coming back for me.  I have confirmed it works. I will look forward to next release.  

PS. Thank you for this awesome nuget package. Our team have had really thankful to you and all contributors.

**Comment by jedusei** [comment]
Hi @NishiokaTakeo 

>Thank you for coming back for me. I have confirmed it works. I will look forward to next release.

Thanks for testing. I have published the release, so you can update the Nuget package now. Sorry for any inconveniences caused by this issue.

>PS. Thank you for this awesome nuget package. Our team have had really thankful to you and all contributors.

You're welcome. 🙂
