### ISSUE TITLE
Implements IConversationsClientListener to recieve events.

### ISSUE THREAD

**Issue by NishiokaTakeo** [jedusei/Twilio.Conversations.Xamarin#3]
Hi, I am trying to implement `IConversationsClientListener `to recieve `OnClientSynchronization()` event in Xamarin. 

I created a class and implement IConversationsClientListener interface. there was no syntax error. But as soon as I build the project my Visual Studio says

`Error XA4212: Type ConversationsClientListener implements Android.Runtime.IJavaObject but does not inherit Java.Lang.Object or Java.Lang.Throwable. This is not supported.MyProject.Android`

I have read an article [Exploring the Conversations Android Quickstart ] (https://www.twilio.com/docs/conversations/android/exploring-conversations-android-quickstart#) and tried to follow the implementation. My implementation way might be wrong?

Can you please help me how to implement events?

Thank you for any help!

**Comment by slimethefrozen** [comment]
Use a pattern like this:
```
public class ActionListener<T> : CallbackListener<T> where T : class, Android.Runtime.IJavaObject
```

Hopefully that'll fix your error.

**Comment by NishiokaTakeo** [comment]
Hi slimethefrozen,

Thank you for replying. I have tried like below, 

`public class TwilioChatService :  Java.Lang.Object, IConversationsClientListener, Android.Runtime.IJavaObject`

It seems the error has passed but new error came..

_Error		java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj\Debug\110\lp\134\jl\bin\classes.jar : com/getkeepsafe/relinker/ApkLibraryInstaller$ZipFileInZipEntry.class	MyClient.Android_			
		
Updated: 
Implement of IConversationsClientListener will introduced below methods and it can be removed when Java.Lang.Object is inherited.
```
IntPtr Handle
int JniIdentityHashCode
JniObjectReference PeerReference
JniPeerMembers JniPeerMembers
JniManagedPeerStates JniManagedPeerState
```

**Comment by slimethefrozen** [comment]
Sorry -- I should have looked at your original post closer:

This is what I use for my Listener:

```
public class AConversationListener : Java.Lang.Object, IConversationsClientListener
```

Also, I'm using an older version of this plugin, so maybe the above pattern has changed.

**Comment by jedusei** [comment]
Hi @NishiokaTakeo
@slimethefrozen is right. Java.Lang.Object already implements Android.Runtime.IJavaObject, so you don't have to declare that as part of your class definition.

Your class definition should look like this:
`public class TwilioChatService : Java.Lang.Object, IConversationsClientListener
`

**Comment by NishiokaTakeo** [comment]
Hi @jedusei @slimethefrozen

Thank you for helping me. I changed the class definition as suggested but same build error but no syntax error.

`public class TwilioChatService : Java.Lang.Object, IConversationsClientListener`

I also have tried all previous versions of the library but all gets same error when build the solution. 

_java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj\Debug\110\lp\134\jl\bin\classes.jar : com/getkeepsafe/relinker/ApkLibraryInstaller$ZipFileInZipEntry.class MyClient.Android_

_Exception in thread "main" java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj\Debug\110\lp\134\jl\bin\classes.jar:com/getkeepsafe/relinker/ApkLibraryInstaller$ZipFileInZipEntry.class_

I noticed there is also this warning.
_warning XBD100: ItemGroup `XamarinBuildDownloadRestoreAssemblyAar` is no longer supported.  If your build is failing, revert to an older Xamarin.Build.Download version, or migrate your packages to use the new `XamarinBuildDownloadAndroidAarLibrary`_ 

Updated:
Visual Studio 2022

**Comment by jedusei** [comment]
@NishiokaTakeo 

It seems to me that the build error is unrelated to your `TwilioChatService` class (unless the error disappears if you remove `IConversationsClientListener` from the class definition).

I also use VS2022 but I have never encountered this error. I think the error is related to the [Xamarin.Relinker](https://www.nuget.org/packages/Xamarin.ReLinker) package that is referenced by Twilio.Conversations.Xamarin.

Have you tried the [latest beta version](https://www.nuget.org/packages/Twilio.Conversations.Xamarin/2.0.0-beta1) of the library? If not, please do so, clean the solution, rebuild, and let me know whether it works.

**Comment by NishiokaTakeo** [comment]
Hi @jedusei 

Thank you for replying. I have installed [Twilio.Conversations.Xamarin with latest beta version](https://www.nuget.org/packages/Twilio.Conversations.Xamarin/2.0.0-beta1). 

It seems the error has disappeared! However sorry, Two new methods are now disappeared.

```
IMessage.Options()
IConversation.SendMessageAsync()
```

Have these moved to somewhere?

**Comment by jedusei** [comment]
@NishiokaTakeo 
You have to use `IConversation.PrepareMessage()` to get a message builder instance (it's similar to `IMessage.Options`). The message builder can be used to create & send the message.
I've also mentioned that here: https://github.com/jedusei/Twilio.Conversations.Xamarin/issues/2#issuecomment-1161262591

**Comment by NishiokaTakeo** [comment]
Hi @jedusei 

Thank you for the information. I have updated. But as soon as solved the error and build. The error comes up again.


`Error		java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj\Debug\110\lp\131\jl\bin\classes.jar : com/getkeepsafe/relinker/ApkLibraryInstaller$ZipFileInZipEntry.class	MyClient.Android			`

**Comment by jedusei** [comment]
@NishiokaTakeo 

Alright try this:

1. Create a new Xamarin.Android project
2. Install the Twilio.Conversations.Xamarin project
3. Build the solution

Let me know whether the error shows up in the new solution or not.

**Comment by NishiokaTakeo** [comment]
Hi @jedusei 

I have tried and it was no errors on new solution. So I discard my all changes on my issued solution. Then just install Twilio.Conversations.Xamarin library. No file changes have been made. 

The error started appearing.

**Comment by jedusei** [comment]
@NishiokaTakeo 
It looks like there's some sort of conflict between the Twilio package and another package in your project.

First, try updating all the packages in the project to their latest versions and rebuild. If you still get the error, then do this:

1. In the new project, install a package that is in your old project & build.
2. If you don't get that error, then remove the package repeat step 1 with a different package from your old project.
3. If you do, then it means that is the package that is conflicting with the Twilio package. 

Repeat the steps until you find the problematic package, then you can let me know which one it is. If you think that package is not necessary for you, you can just uninstall it from your project.

**Comment by NishiokaTakeo** [comment]
@jedusei 

Thank you for replying. 
Installing below nuget packages with Twilio.Conversations.Xamarin packages. Following errors appeared.

Com.Getkeepsafe.Relinker(v1.3.1) caused issues
`java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj\Debug\120\lp\1\jl\bin\classes.jar : com/getkeepsafe/relinker/BuildConfig.class`

Twilio.Chat.Xamarin(0.7.2)
`java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj\Debug\120\lp\1\jl\bin\classes.jar : com/getkeepsafe/relinker/BuildConfig.class`


I am still checking and will post if I found others.

**Comment by jedusei** [comment]
@NishiokaTakeo 
Yes that's exactly the package causing the issue. The Twilio Conversations SDK requires version 1.4.4 of Relinker, so that's what the Twilio.Conversations.Xamarin nuget package uses. You have to uninstall Com.Getkeepsafe.Relinker to remove the build errors.

**Comment by NishiokaTakeo** [comment]
@jedusei 

Thank you for helping me. 

I uninstall Com.Getkeepsafe.Relinker(v1.3.1)  and install Xamarin.ReLinker (v1.4.4).  The error was still appearing.

So I keep investigating and finally succeeded the building b y uninstalling

- Com.Getkeepsafe.Relinker
- Twilio.Chat.Xamarin

then install Xamarin.Relinker
then upgrade Xamarin.Kotlin.StdLib(>= 1.5.31.1)

Really thank you for a quick response and help.

**Comment by jedusei** [comment]
@NishiokaTakeo 

That's great to hear! You're welcome. 🙂
