### ISSUE TITLE
GetUnreadMessagesCountAsync() causes NullReferenceException

### ISSUE THREAD

**Issue by NishiokaTakeo** [jedusei/Twilio.Conversations.Xamarin#4]
Hi,

I am trying to get unreaded messages counts in android project. I have two conversations and one can get the count but second one cause NullReferenceException. 

            var orderedConversations = IConversationClient.MyConversations.OrderByDescending(x => x.CreatedBy);

            foreach (var elm in orderedConversations)
            {
                // This success  at second loop.
                var currentConversation = await _chatClient.GetConversationAsync(elm.Sid);
                
                // this cause null reference exception at second loop.
                await currentConversation.GetUnreadMessagesCountAsync();
            }

Error : 
```
{System.NullReferenceException: Object reference not set to an instance of an object.
  at Twilio.Conversations.IConversation.GetUnreadMessagesCountAsync () [0x0002b] in C:\Users\Joe\source\repos\Twilio.Conversations.Xamarin\Twilio.Conversations.Droid\Additions\IConversation.cs:82 
  at MobilityClient.Droid.TwilioChat.TwilioChatService.GetUserChannels ()  }
```

Any help would be very thank you.

**Comment by slimethefrozen** [comment]
You should include a null check on currentConversation - not guaranteed a non-null result from that.

You should also throw a conditional on the .Sid, like this:

```
        var orderedConversations = IConversationClient.MyConversations.OrderByDescending(x => x.CreatedBy);

        foreach (var elm in orderedConversations)
        {
            // This success  at second loop.
            var currentConversation = await _chatClient.GetConversationAsync(elm?.Sid);
            if (currentConversation != null) {
               // this cause null reference exception at second loop.
               await currentConversation.GetUnreadMessagesCountAsync();
               }
        }
```

**Comment by NishiokaTakeo** [comment]
Hi @slimethefrozen 

Thank you for replying. `elm.Sid` has a value and also `currentConversation `is not null. It seems inside of `GetUnreadMessagesCountAsync()` methods throwing the exception. 

I have just tried NonAsync method below and result from the sdk is null.

```
 var task = new AsyncCallbackListener<Java.Lang.Long>();
 currentConversation.GetUnreadMessagesCount(task);
 var unreadedCount = await task.GetResultAsync(); // unreadedCount == null
```

So it throws at Additions\IConversation.cs:82

```
public async Task<long> GetUnreadMessagesCountAsync()
{
        var listener = new AsyncCallbackListener<Java.Lang.Long>();
        GetUnreadMessagesCount(listener);
        return (await listener.GetResultAsync()).LongValue(); // <----- Here null.LongValue() == throws null exception
}
```

I have just read the document and getUnreadMessagesCountAsync() on Android SDK has a possibility to return null.

>  if the last read index has not been yet set for current user as the participant of this conversation then unread messages count is considered uninitialized. In this case null is returned.

http://media.twiliocdn.com/sdk/android/conversations/releases/3.1.0/docs/-conversations%20-android%20-s-d-k/com.twilio.conversations/-conversation/get-unread-messages-count.html?query=abstract%20fun%20getUnreadMessagesCount(listener:%20CallbackListener%3CLong%3E)

**Comment by jedusei** [comment]
Hi @NishiokaTakeo 

Thanks for pointing this out. I just found out that `GetUnreadMessagesCount()` will return null until a method that modifies the unread message count is called on the conversation (`SetAllMessagesRead()`, `SetAllMessagesUnread`, etc.). I'll fix this in the next release.

For now, you can use this code to get the unread message count:
```
var listener = new AsyncCallbackListener<Java.Lang.Long>();
currentConversation.GetUnreadMessagesCount(listener);
long unreadMessageCount = (await listener.GetResultAsync())?.LongValue() ?? 0L;
```

**Comment by NishiokaTakeo** [comment]
Hi @jedusei and @slimethefrozen 

Thank you for helping me. :)
