### ISSUE TITLE
GetConversationAsync and IConversationClient.MyConversations does not return conversation.

### ISSUE THREAD

**Issue by NishiokaTakeo** [jedusei/Twilio.Conversations.Xamarin#7]
Hi,

I am trying to get conversation through `GetConversationAsync()` and `IConversationClient.MyConversations` property. The codes below does not return `IConversation` in Android app in Xamarin.

I have had following codes in server. 
```
var channel = await ConversationResource.CreateAsync(friendlyName: "1:2", uniqueName: "1:2");
ParticipantResource.CreateAsync(channel.Sid, "1");
ParticipantResource.CreateAsync(channel.Sid, "2");

// Then these below codes gets conversation and participants.
var channelResult = await ConversationResource.FetchAsync(pathSid: "1:2");
var participants = ParticipantResource.Read(
     pathConversationSid: channel.Sid,
     limit: 20);
```

In the Android app, I run the codes below. conversationClient is IConversationClient instance and it initialised with `Completed status.`

```
var conversation1 = conversationClient.MyConversations.FirstOrDefault(x => x.Sid == channelIdString); // <--- return null
var conversation2 = await conversationClient.GetConversationAsync(channelId); // <--- timeout or never gets return value. 
```

I have investigated with google and my codes but it did not help. Any help would be very thank you.

**Comment by jedusei** [comment]
Hi @NishiokaTakeo 

I have been able to reproduce the timeout issue in `GetConversationAsync()` and I'm working on a fix for that. However, I am unable to reproduce the first issue. I can get the conversation from the `MyConversations` property. Are you sure `channelIdString` is a valid Twilio SID, and that the conversation client is connected as the right participant?

**Comment by NishiokaTakeo** [comment]
Hi @jedusei 

Thank you for reply. I have checked `channelIdString `is the valid "CHXXX..." Id. One of That _channel (conversation)_'s participant includes `identity: "1"`. Also an android app is using a token that was generated with `identity: "1"`.

So `IConversationClient.MyUser.Identity` == `a channel (conversation) participant identity`

**Comment by jedusei** [comment]
@NishiokaTakeo 

Is that user part of any other conversations?
If not please add the user to another conversation and then check whether `MyConversations.Count > 0`.
I cannot reproduce this issue on my end. I am able to see the list of conversations after the client has been synchronized.

**Comment by NishiokaTakeo** [comment]
Hi @jedusei 

The user is part of other conversations and I can see some conversations in `MyConversations `property.  it seems `MyConversations.Count()` does not increase after creating new conversation with participants. How would you created new conversation and participants? I created them at backend. Is there any caches for MyConversations?

**Comment by jedusei** [comment]
Hi @NishiokaTakeo 

`IConversationsClientListener.OnConversationAdded` will be called when the user is added to a conversation. I think `MyConversations.Count` is also updated automatically. `MyConversations` is not cached, as far as I know. Are you sure you're adding the correct user to the conversation?

**Comment by NishiokaTakeo** [comment]
Hi @jedusei 

Thank you for helping me and these information. I have checked and `IConversationsClientListener.OnConversationAdded` is not called when I add a participant to a conversation. 

> Are you sure you're adding the correct user to the conversation

I have checked it. Probably I would not add the correct a user to the conversation. I have created new conversation by _IConversationClient.CreateConversation()_ . I then get Sid and Fetch the conversation by that Sid. It throws Not Found Exception in back end. However, I can find the conversation by that Sid and participants by `GetParticipantsByIdentity()`. 

I am not sure why this happens. Identity is same. token was generated by that identity and created a participant by that identity...

**Comment by jedusei** [comment]
Hi @NishiokaTakeo 

I have published a new release, so you can update the package and use `GetConversationAsync()` now. Please note that `GetConversationAsync()` will throw an exception if the conversation is not found.

> It throws Not Found Exception in back end.

If you aren't using the default conversation service in the backend then you have to pass the conversation service SID as shown [here.](https://www.twilio.com/docs/conversations/api/service-conversation-resource?code-sample=code-create-conversation&code-language=C%23&code-sdk-version=5.x#linkcode) If that's not the cause of the problem then I'm afraid I cannot help any further unless I see some more code.

**Comment by NishiokaTakeo** [comment]
Good morning @jedusei ,

Thank you for replying and helping me a lots! Yes. I noticed I had not used right conversation service when I create/fetch the conversations/participants resources. But creating token was used not default one. I also noticed using namespace was wrong.

This is for other devs like me, please be careful namespaces in the backend. There are same resource classes to create/fetch/delete/update for conversation/users/participant.

- `Twilio.Rest.Conversations.V1` and `Twilio.Rest.Conversations.V1.Conversation` namespace is basically using default conversation service. 
- `Twilio.Rest.Conversations.V1.Service` and `Twilio.Rest.Conversations.V1.Service.Conversation` namespace is using conversation service depends. You needs to always specify conversation service Ids (ISXXX...). 

Thank you @jedusei !

**Comment by jedusei** [comment]
You're welcome @NishiokaTakeo
